### ISSUE TITLE
make it friends with template(lang="pug")

### ISSUE THREAD

**Issue by denis-gorin** [mrodal/vue-inheritance-loader#1]
hi, thanks for this great solution!

it works exactly what I need
But one little moment - I use pug, so I had to convert my templates, wich I'd like to chain in inheritance, back to html, my eyes are bleeding now, but I will survive

**Comment by mrodal** [comment]
Hey @denis-gorin, Im glad you liked it! 

Doesn't pug already provide extending templates? Look at [this](https://medium.com/js-dojo/extending-vuejs-components-42fefefc688b)

**Comment by denis-gorin** [comment]
Yes thats a good right way, thanks, it's more better than combine html and pug, but less excellent in one-file component paradigm
