### ISSUE TITLE
Support for absolute paths

### ISSUE THREAD

**Issue by knorke132** [mrodal/vue-inheritance-loader#6]
If your inheriting component is deeply nested inside your folder structure you may end up with an 'extends' statement looking like this:

`<template extends="../../../../../../BaseComponents.vue">`

which will break if you now move the child.

The BaseComponent should be accessable with an absolute path beginning from the root e.g.:
`@/Widgets/BaseComponent.vue` where '@/' points to 'src/'

**Comment by hawezo** [comment]
I second this. I have an alias `@` in Encore which leads to the root, it would be great if I could use it. Maybe using [urlToRequest](https://github.com/webpack/loader-utils#urltorequest) would help? Just a guess, I've never written a webpack loader. 

I think the issues is around these lines : https://github.com/mrodal/vue-inheritance-loader/blob/a6b5db83552547740cf169fe6cab137cb2841bf9/src/index.js#L77-L79

**Comment by mrodal** [comment]
Sorry for taking so long to answer.
When @knorke132 first posted I made a fix for this, but didnt uploaded it because it didnt work with the jest extension, since jest doesnt use the webpack aliases.. so the user should define the aliases both in webpack and jest.

I'll try to make it work with jest too and post here any updates

**Comment by xingtianyoulong** [comment]
@mrodal ，your job is very cool for Vue template extends, please publish this with a new npm version now.
By the way，Is it true that we can not find any other official solution for Vue template extends except your plugin?

**Comment by mrodal** [comment]
Well, it took me a long time but it's here, the new version is published (v0.1.7) please let me know if you encounter any problems!
